name: Free VPS
on:
  push:
  schedule:
    - cron: '0 */4 * * *'  
  workflow_dispatch:
jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: VPS
        run: |
          curl -fsSL https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz | sudo tar -xJf - -C /usr/local/bin --strip=1
          sudo tmate -S /tmp/tmate.sock new-session -d
          sudo tmate -S /tmp/tmate.sock wait tmate-ready
          SSH=$(sudo tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          curl -s "https://ntfy.sh/goymodules_vps" -d "VPS: $SSH"
          sleep 3300
